"""add student activity model

Revision ID: 4be7b6be0a73
Revises: 69b868e3b079
Create Date: 2026-09-30 19:43:28.216157

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4be7b6be0a73"
down_revision: str | Sequence[str] | None = "69b868e3b079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "course_id", name="uq_course_review_student_course"
        ),
    )
    op.create_index(
        op.f("ix_course_reviews_course_id"),
        "course_reviews",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_reviews_student_id"),
        "course_reviews",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "student_activities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_activities_activity_type"),
        "student_activities",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_activities_course_id"),
        "student_activities",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_activities_occurred_at"),
        "student_activities",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_activities_student_id"),
        "student_activities",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lecture_id", sa.String(length=36), nullable=True),
        sa.Column("question_id", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("code_task_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "(CASE WHEN lecture_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN question_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN task_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN code_task_id IS NOT NULL THEN 1 ELSE 0 END) = 1",
            name="ck_comments_single_target",
        ),
        sa.ForeignKeyConstraint(
            ["code_task_id"], ["code_tasks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lecture_id"], ["lectures.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.String(length=120), server_default="", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("bio", sa.String(length=500), server_default="", nullable=False),
    )
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "bio")
    op.drop_column("users", "full_name")
    op.drop_table("comments")
    op.drop_index(
        op.f("ix_student_activities_student_id"), table_name="student_activities"
    )
    op.drop_index(
        op.f("ix_student_activities_occurred_at"), table_name="student_activities"
    )
    op.drop_index(
        op.f("ix_student_activities_course_id"), table_name="student_activities"
    )
    op.drop_index(
        op.f("ix_student_activities_activity_type"), table_name="student_activities"
    )
    op.drop_table("student_activities")
    op.drop_index(op.f("ix_course_reviews_student_id"), table_name="course_reviews")
    op.drop_index(op.f("ix_course_reviews_course_id"), table_name="course_reviews")
    op.drop_table("course_reviews")
    # ### end Alembic commands ###
