"""course lifecycle status

Revision ID: 77b36d7d3d24
Revises: a14ce61d2ddd
Create Date: 2026-09-21 00:07:12.329344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b36d7d3d24'
down_revision: Union[str, Sequence[str], None] = 'a14ce61d2ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'courses',
        sa.Column(
            'status',
            sa.String(length=32),
            nullable=False,
            server_default='published',
        ),
    )
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
